services:
  - type: web
    name: whatsa-king
    env: static
    staticPublishPath: ./docs
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
